### ISSUE TITLE
Objective 1: Make django app and push on heroku

### ISSUE THREAD

**Issue by jihounim** [albertkao123/whenIsGreat#1]

**Comment by caprexy** [comment]
Created mini django website using this:
https://docs.djangoproject.com/en/3.2/intro/tutorial01/

following this to setup heroku on my own acc
https://devcenter.heroku.com/articles/getting-started-with-python?singlepage=true

Need this speical command 
git subtree push --prefix backend heroku master

Had to run 
heroku config:set DISABLE_COLLECTSTATIC=1 
was causing issues about static stuff idk

**Comment by caprexy** [comment]
hot trash found here: https://whenisgreat.herokuapp.com/
